export const KMDistanceBetweenOneDegreeLatitude = 111;
export const KMDistanceBetweenOneDegreeLongitudeAtMax = 111.321;
export const milesBetweenOneDegreeOfLongitudeAtMax = 69.172;
export const oneMileAsKM = 1.609344; // 1.609344 km.
export const oneKMAsAMile = 0.6214;
export const maxDegreesLatitude = 90;
export const latitudeAtEquator = 0; // mostly here as a reminder
export const minDegreesLatitude = -90;
export const maxDegreesLongitude = 180;
export const longitudeAtPrimeMeridian = 0; // mostly here as a reminder
export const minDegreesLongitude = -180;
