import { GymCreationAttributes } from "../../database/models/Gym";

export const Brampton = [
    {
        gymId: 481,
        cityName: "Brampton",
        address: "227 Vodden St E, Brampton, ON L6V 1N2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7026949,
        long: -79.7567502,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Planet Fitness",
        rating: 3.9,
        cityId: 8,
    },
    {
        gymId: 482,
        cityName: "Brampton",
        address: "10906 Hurontario Street D 4,5 & 6, Brampton, ON L7A 3R9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7248214,
        long: -79.8135003,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.5,
        cityId: 8,
    },
    {
        gymId: 483,
        cityName: "Brampton",
        address: "370 Main St N, Brampton, ON L6V 4A4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.695925,
        long: -79.771056,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Brampton Kingspoint Plaza",
        rating: 4.1,
        cityId: 8,
    },
    {
        gymId: 484,
        cityName: "Brampton",
        address: "25 Peel Centre Dr, Brampton, ON L6T 3R5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.71546,
        long: -79.72169799999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Brampton Bramalea City Centre",
        rating: 4,
        cityId: 8,
    },
    {
        gymId: 485,
        cityName: "Brampton",
        address: "10088 McLaughlin Rd, Brampton, ON L7A 2X6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.696262,
        long: -79.80041299999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Brampton McLaughlin Corners West",
        rating: 4.1,
        cityId: 8,
    },
    {
        gymId: 486,
        cityName: "Brampton",
        address: "35 Resolution Dr Unit J08, Brampton, ON L6W 0A6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6791451,
        long: -79.7210396,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.1,
        cityId: 8,
    },
    {
        gymId: 487,
        cityName: "Brampton",
        address: "315 Royal West Drive Unit F-G, Brampton, ON L6X 5K8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6599444,
        long: -79.8145579,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4,
        cityId: 8,
    },
    {
        gymId: 488,
        cityName: "Brampton",
        address: "11765 Bramalea Rd, Brampton, ON L6R 3S9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.771637,
        long: -79.77758299999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Brampton Mayfield and Bramalea",
        rating: 4,
        cityId: 8,
    },
    {
        gymId: 489,
        cityName: "Brampton",
        address: "9446 McLaughlin Rd N #16, Brampton, ON L6X 4H9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6844749,
        long: -79.7833358,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Quick Fitness",
        rating: 4.5,
        cityId: 8,
    },
    {
        gymId: 490,
        cityName: "Brampton",
        address: "499 Main St S, Brampton, ON L6Y 1N9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.666156,
        long: -79.73786199999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Brampton Gateway",
        rating: 3.8,
        cityId: 8,
    },
    {
        gymId: 491,
        cityName: "Brampton",
        address: "164 Sandalwood Pkwy E Unit 125, Brampton, ON L6Z 3S4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7277193,
        long: -79.7972004,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "7X Fitness for Women",
        rating: 4.8,
        cityId: 8,
    },
    {
        gymId: 492,
        cityName: "Brampton",
        address: "20 Polonia Ave Unit 107, Brampton, ON L6Y 0K9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6425551,
        long: -79.761454,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fuzion Fitness Brampton",
        rating: 3.8,
        cityId: 8,
    },
    {
        gymId: 493,
        cityName: "Brampton",
        address: "30 Hale Rd Unit 13, Brampton, ON L6W 4N9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6856868,
        long: -79.7207802,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "TrainMeFit Brampton",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 494,
        cityName: "Brampton",
        address: "539 Steeles Ave E, Brampton, ON L6W 4S2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6764112,
        long: -79.7203749,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 4,
        cityId: 8,
    },
    {
        gymId: 495,
        cityName: "Brampton",
        address: "9145 Airport Rd, Brampton, ON L6S 0C2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.747594,
        long: -79.69993199999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Brampton Woodhill Gym",
        rating: 4,
        cityId: 8,
    },
    {
        gymId: 496,
        cityName: "Brampton",
        address: "225 Fletchers Creek Blvd, Brampton, ON L6X 0Y7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6920184,
        long: -79.7999931,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 3.9,
        cityId: 8,
    },
    {
        gymId: 497,
        cityName: "Brampton",
        address: "2959 Bovaird Dr E, Brampton, ON L6T 3S1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7596596,
        long: -79.72438819999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 3.5,
        cityId: 8,
    },
    {
        gymId: 498,
        cityName: "Brampton",
        address: "65 Montpelier St, Brampton, ON L6Y 6H4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6344084,
        long: -79.78599439999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "F45 Training New Brampton",
        rating: 4.9,
        cityId: 8,
    },
    {
        gymId: 499,
        cityName: "Brampton",
        address: "20 Union St, Brampton, ON L6V 1R2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.688879,
        long: -79.7589571,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Brampton YMCA",
        rating: 4.2,
        cityId: 8,
    },
    {
        gymId: 500,
        cityName: "Brampton",
        address: "284 Orenda Rd Unit 10, Brampton, ON L6T 5S3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7004668,
        long: -79.7138457,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "RGX Fitness",
        rating: 4.8,
        cityId: 8,
    },
    {
        gymId: 501,
        cityName: "Brampton",
        address: "9025 Torbram Rd, Brampton, ON L6S 5X9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7351764,
        long: -79.707072,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit4Less",
        rating: 4,
        cityId: 8,
    },
    {
        gymId: 502,
        cityName: "Brampton",
        address: "995 Peter Robertson Blvd, Brampton, ON L6R 2E9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7492915,
        long: -79.7428335,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Chinguacousy Wellness Centre",
        rating: 4.3,
        cityId: 8,
    },
    {
        gymId: 503,
        cityName: "Brampton",
        address: "75 Rosedale Ave W Unit 1, Brampton, ON L6X 4H4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6867485,
        long: -79.77119569999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Total Body Fitness & Wellness",
        rating: 4.8,
        cityId: 8,
    },
    {
        gymId: 504,
        cityName: "Brampton",
        address: "125 Chrysler Dr Unit 9, Brampton, ON L6S 6L1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7412223,
        long: -79.70355980000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "My Bollywood Body",
        rating: 4.9,
        cityId: 8,
    },
    {
        gymId: 505,
        cityName: "Brampton",
        address: "2120 N Park Dr Unit 27, Brampton, ON L6S 0C9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7507998,
        long: -79.7267107,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "F45 Training North Park Brampton",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 506,
        cityName: "Brampton",
        address: "North, 630 Peter Robertson Blvd, Brampton, ON L6R 1T4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7406506,
        long: -79.7602276,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Crunch Fitness - Brampton North",
        rating: 2.9,
        cityId: 8,
    },
    {
        gymId: 507,
        cityName: "Brampton",
        address: "3960 Cottrelle Blvd, Brampton, ON L6P 2R1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7844085,
        long: -79.6615691,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 3.3,
        cityId: 8,
    },
    {
        gymId: 508,
        cityName: "Brampton",
        address: "499 Main St S Unit #105, Brampton, ON L6Y 1N7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.666146,
        long: -79.737557,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit4Less",
        rating: 3.3,
        cityId: 8,
    },
    {
        gymId: 509,
        cityName: "Brampton",
        address: "10150 The Gore Rd, Brampton, ON L6P 0A6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7938182,
        long: -79.6942741,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "The Gym",
        rating: 4.4,
        cityId: 8,
    },
    {
        gymId: 510,
        cityName: "Brampton",
        address: "170 Bovaird Dr W Unit 10, Brampton, ON L7A 1A1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7044188,
        long: -79.7895565,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "FITFORGOOD",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 511,
        cityName: "Brampton",
        address: "35 Worthington Ave, Brampton, ON L7A 2Y7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.683695,
        long: -79.815491,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit4Less",
        rating: 3.5,
        cityId: 8,
    },
    {
        gymId: 512,
        cityName: "Brampton",
        address: "210 Great Lakes Dr, Brampton, ON L6R 2K7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.73227199999999,
        long: -79.76633400000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit4Less",
        rating: 3.4,
        cityId: 8,
    },
    {
        gymId: 513,
        cityName: "Brampton",
        address: "456 Vodden St E Unit 11, Brampton, ON L6S 5V1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/shopping-71.png",
        lat: 43.71393,
        long: -79.74652999999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/shopping-71.png",
        name: "Free Bird Health Club Brampton",
        rating: 4.9,
        cityId: 8,
    },
    {
        gymId: 514,
        cityName: "Brampton",
        address: "8275 Financial Dr, Brampton, ON L6Y 5G8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6349291,
        long: -79.7880884,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 3.2,
        cityId: 8,
    },
    {
        gymId: 515,
        cityName: "Brampton",
        address: "18 Strathearn Ave, Brampton, ON L6T 4P1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.69475569999999,
        long: -79.69855679999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "NashDFitness",
        rating: 4.6,
        cityId: 8,
    },
    {
        gymId: 516,
        cityName: "Brampton",
        address: "160 Main St S Unit# 10, Brampton, ON L6W 2E1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6782516,
        long: -79.7476109,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Wellness Oasis Gym",
        rating: 4.3,
        cityId: 8,
    },
    {
        gymId: 517,
        cityName: "Brampton",
        address: "5 Resolution Dr, Brampton, ON L6W 4R9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6812145,
        long: -79.71942969999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Planet Fitness",
        rating: 4,
        cityId: 8,
    },
    {
        gymId: 518,
        cityName: "Brampton",
        address: "47 Queen St E, Brampton, ON L6W 2A7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6866884,
        long: -79.7587162,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "A1 Fitness Studio",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 519,
        cityName: "Brampton",
        address: "10 Henderson Ave Unit #4, Brampton, ON L6Y 2A4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6783653,
        long: -79.7635557,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Signature Shape FitCamp for Women",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 520,
        cityName: "Brampton",
        address: "4 Abacus Rd #1, Brampton, ON L6T 5J6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7638104,
        long: -79.6617007,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Edge Fitness & Performance",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 521,
        cityName: "Brampton",
        address: "15 Regan Rd Unit 4, Brampton, ON L7A 1E3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7012591,
        long: -79.8005185,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Lions Cage MMA & Fitness",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 522,
        cityName: "Brampton",
        address: "4 Automatic Rd #106, Brampton, ON L6S 5P2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 43.7548705,
        long: -79.7087529,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "King Of The Ring Boxing Club & Fitness",
        rating: 4.4,
        cityId: 8,
    },
    {
        gymId: 523,
        cityName: "Brampton",
        address: "10 Henderson Ave, Brampton, ON L6Y 2A4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6783018,
        long: -79.76353929999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "The Weighting Room",
        rating: 4.5,
        cityId: 8,
    },
    {
        gymId: 524,
        cityName: "Brampton",
        address: "8500 Torbram Rd Unit# 54, Brampton, ON L6T 5C6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7240011,
        long: -79.6937533,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Strength Camp Toronto",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 525,
        cityName: "Brampton",
        address: "284 Orenda Rd unit 9, Brampton, ON L6T 5S3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7004801,
        long: -79.7139778,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Benchmark Sports",
        rating: 4.2,
        cityId: 8,
    },
    {
        gymId: 526,
        cityName: "Brampton",
        address: "55 Regan Rd #1, Brampton, ON L7A 1B2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 43.7074763,
        long: -79.8070288,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "All Star Sports Centre",
        rating: 4.5,
        cityId: 8,
    },
    {
        gymId: 527,
        cityName: "Brampton",
        address: "68 Doris Pawley Cres, Caledon, ON L7C 4E7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7545862,
        long: -79.8150929,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fitnesspros Canada - Brampton & Caledon's #1 Personal Training & Lifestyle Program",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 528,
        cityName: "Brampton",
        address: "456 Vodden St E, Brampton, ON L6S 5V1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.713902,
        long: -79.7465193,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Free Bird Nutrition Brampton Supplement store\ud83e\udd85",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 529,
        cityName: "Brampton",
        address: "40B Hansen Rd S, Brampton, ON L6W 3H4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 43.6955992,
        long: -79.73937409999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "DoggPound Martial Arts & Fitness Academy",
        rating: 4.9,
        cityId: 8,
    },
    {
        gymId: 530,
        cityName: "Brampton",
        address: "8550 Torbram Rd, Brampton, ON L6T 5C8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 43.7247903,
        long: -79.69518459999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "Champion Boxing Club",
        rating: 4.6,
        cityId: 8,
    },
    {
        gymId: 531,
        cityName: "Brampton",
        address: "29 Kettlewell Crescent, Brampton, ON L6R 0T2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.779365,
        long: -79.745357,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fitness Mantra In Home Personal Trainer",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 532,
        cityName: "Brampton",
        address: "11 Calmist Crescent, Brampton, ON L6Y 4L6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6575785,
        long: -79.7606984,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "PNW Studios Consulting and Wellness",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 533,
        cityName: "Brampton",
        address: "25 Kings Cross Rd Unit 5A, Brampton, ON L6T 3V5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 43.7205099,
        long: -79.7180395,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "Red Owl Boxing - The Owl's Nest",
        rating: 4.4,
        cityId: 8,
    },
    {
        gymId: 534,
        cityName: "Brampton",
        address: "8200 Dixie Rd, Brampton, ON L6T 4B8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7037207,
        long: -79.71641369999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Rogers Fitness Centre",
        rating: 4.3,
        cityId: 8,
    },
    {
        gymId: 535,
        cityName: "Brampton",
        address: "6 George St S, Brampton, ON L6Y 1L9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 43.6849114,
        long: -79.7601837,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "Futbol Strength Academy",
        rating: 4.9,
        cityId: 8,
    },
    {
        gymId: 536,
        cityName: "Brampton",
        address: "240 Clarence St unit 4/5, Brampton, ON L6W 1T4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.691456,
        long: -79.7370081,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Gymnastic Giants",
        rating: 3.6,
        cityId: 8,
    },
    {
        gymId: 537,
        cityName: "Brampton",
        address: "40 Lollard Wy, Brampton, ON L6Y 0E4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6337469,
        long: -79.8016744,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Body Experience",
        rating: 5,
        cityId: 8,
    },
    {
        gymId: 538,
        cityName: "Brampton",
        address: "284 Orenda Rd Unit 8, Brampton, ON L6T 5S3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.700479,
        long: -79.7140247,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Toprock Climbing",
        rating: 4.9,
        cityId: 8,
    },
    {
        gymId: 539,
        cityName: "Brampton",
        address: "2 Automatic Rd Unit 120, Brampton, ON L6S 6K9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 43.7548967,
        long: -79.7080084,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "Hot Yoga Wellness Brampton",
        rating: 4.6,
        cityId: 8,
    },
    {
        gymId: 540,
        cityName: "Brampton",
        address: "253 Summerlea Rd, Brampton, ON L6T 5A8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 43.735921,
        long: -79.7004829,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "Legends MMA",
        rating: 5,
        cityId: 8,
    },
];
