import { GymCreationAttributes } from "../../database/models/Gym";

export const Mississauga = [
    {
        gymId: 421,
        cityName: "Mississauga",
        address: "1452-1454 Dundas St E, Mississauga, ON L4X 1L4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.610099,
        long: -79.581785,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Planet Fitness",
        rating: 4.3,
        cityId: 7,
    },
    {
        gymId: 422,
        cityName: "Mississauga",
        address: "1590 Dundas St E, Mississauga, ON L4X 2Z2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6138902,
        long: -79.57813320000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fuzion Fitness Mississauga",
        rating: 4.8,
        cityId: 7,
    },
    {
        gymId: 423,
        cityName: "Mississauga",
        address: "1151 Dundas St W, Mississauga, ON L5C 1C6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.558241,
        long: -79.6450485,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Planet Fitness",
        rating: 4.1,
        cityId: 7,
    },
    {
        gymId: 424,
        cityName: "Mississauga",
        address: "7-1725 Matheson Blvd, Mississauga, ON L4W 1Z1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6408066,
        long: -79.62292649999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Tempo Fitness & Performance",
        rating: 4.9,
        cityId: 7,
    },
    {
        gymId: 425,
        cityName: "Mississauga",
        address: "1275 Mississauga Vly Blvd, Mississauga, ON L5A 3R8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.597086,
        long: -79.625236,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Mississauga Valley Gymnasium",
        rating: 4.3,
        cityId: 7,
    },
    {
        gymId: 426,
        cityName: "Mississauga",
        address: "3450 Ridgeway Dr Unit #17, Mississauga, ON L5L 0A2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.523571,
        long: -79.7063293,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "PowerHouse Gym Mississauga",
        rating: 3.8,
        cityId: 7,
    },
    {
        gymId: 427,
        cityName: "Mississauga",
        address: "6685 Century Ave, Mississauga, ON L5N 7K2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6030769,
        long: -79.74411769999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Movati Athletic",
        rating: 4.2,
        cityId: 7,
    },
    {
        gymId: 428,
        cityName: "Mississauga",
        address: "4036 Confederation Pkwy, Mississauga, ON L5B 0J6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.58566829999999,
        long: -79.6459763,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.2,
        cityId: 7,
    },
    {
        gymId: 429,
        cityName: "Mississauga",
        address: "2425 Truscott Dr #26, Mississauga, ON L5J 2B4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5129645,
        long: -79.6490453,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Vive Fitness 24/7 Truscott Mississauga",
        rating: 4.8,
        cityId: 7,
    },
    {
        gymId: 430,
        cityName: "Mississauga",
        address: "3555 Hawkestone Rd, Mississauga, ON L5C 2V1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5719859,
        long: -79.6532498,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Hawkestone Fitness",
        rating: 4.9,
        cityId: 7,
    },
    {
        gymId: 431,
        cityName: "Mississauga",
        address: "5757 Kennedy Rd, Mississauga, ON L4Z 0C5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6313486,
        long: -79.660877,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Forge Performance & Fitness",
        rating: 4.7,
        cityId: 7,
    },
    {
        gymId: 432,
        cityName: "Mississauga",
        address: "10 Falconer Dr #7, Mississauga, ON L5N 3L8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5928675,
        long: -79.72552499999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Studio One Fitness",
        rating: 4.9,
        cityId: 7,
    },
    {
        gymId: 433,
        cityName: "Mississauga",
        address: "5030 Satellite Dr Unit D1, Mississauga, ON L4W 0E3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6508906,
        long: -79.6052837,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4,
        cityId: 7,
    },
    {
        gymId: 434,
        cityName: "Mississauga",
        address: "780 Burnhamthorpe Rd W Unit 8, Mississauga, ON L5C 3X3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5770652,
        long: -79.65262419999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "L5 Health and Fitness",
        rating: 4.8,
        cityId: 7,
    },
    {
        gymId: 435,
        cityName: "Mississauga",
        address: "3040 Universal Dr, Mississauga, ON L4X 2C8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6227449,
        long: -79.5710721,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fortis Fitness West",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 436,
        cityName: "Mississauga",
        address: "3087 Winston Churchill Blvd, Mississauga, ON L5L 2V8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5243513,
        long: -79.6833558,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.1,
        cityId: 7,
    },
    {
        gymId: 437,
        cityName: "Mississauga",
        address: "700 Dundas St E, Mississauga, ON L4Y 3Y5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5945773,
        long: -79.59879389999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Huf Gym Inc",
        rating: 4.7,
        cityId: 7,
    },
    {
        gymId: 438,
        cityName: "Mississauga",
        address: "2021 Cliff Rd, Mississauga, ON L5A 3N7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5773036,
        long: -79.5916752,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "One Health Clubs",
        rating: 4,
        cityId: 7,
    },
    {
        gymId: 439,
        cityName: "Mississauga",
        address: "3611 Mavis Rd #12-15, Mississauga, ON L5C 1T7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5789944,
        long: -79.649125,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Habitual Fitness & Lifestyle",
        rating: 4.9,
        cityId: 7,
    },
    {
        gymId: 440,
        cityName: "Mississauga",
        address: "560 Courtneypark Dr W, Mississauga, ON L5W 1L9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6249077,
        long: -79.7041386,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "560 Fitness",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 441,
        cityName: "Mississauga",
        address: "6875 Meadowvale Town Centre Cir, Mississauga, ON L5N 2W7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.582619,
        long: -79.75890199999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Mississauga Meadowvale Town Centre",
        rating: 4,
        cityId: 7,
    },
    {
        gymId: 442,
        cityName: "Mississauga",
        address: "785 Britannia Rd W #3, Mississauga, ON L5V 2X8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.611447,
        long: -79.69997,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Mississauga Heartland Town Centre",
        rating: 3.8,
        cityId: 7,
    },
    {
        gymId: 443,
        cityName: "Mississauga",
        address: "660 Eglinton Ave W, Mississauga, ON L5R 3V2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.59217510000001,
        long: -79.66671099999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 3.8,
        cityId: 7,
    },
    {
        gymId: 444,
        cityName: "Mississauga",
        address: "4561 Hurontario St, Mississauga, ON L4Z 3X3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.60671749999999,
        long: -79.6512204,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 4.1,
        cityId: 7,
    },
    {
        gymId: 445,
        cityName: "Mississauga",
        address: "515 Lakeshore Rd E, Mississauga, ON L5G 1H9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5661451,
        long: -79.5705129,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.5,
        cityId: 7,
    },
    {
        gymId: 446,
        cityName: "Mississauga",
        address: "3075 Ridgeway Dr #21, Mississauga, ON L5L 5X8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.519724,
        long: -79.68928939999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Lion Strong Fitness",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 447,
        cityName: "Mississauga",
        address: "991 Matheson Blvd E, Mississauga, ON L4W 2V3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.63262049999999,
        long: -79.6412747,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fitness NATION",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 448,
        cityName: "Mississauga",
        address: "50 Burnhamthorpe Rd W #68, Mississauga, ON L5B 3C2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5912631,
        long: -79.6362098,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "F45 Training Mississauga Downtown",
        rating: 4.9,
        cityId: 7,
    },
    {
        gymId: 449,
        cityName: "Mississauga",
        address: "3100 Dixie Rd Ste 14a, Mississauga, ON L4Y 2A6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.60947729999999,
        long: -79.5865477,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 3.9,
        cityId: 7,
    },
    {
        gymId: 450,
        cityName: "Mississauga",
        address: "3413 Wolfedale Rd Unit 8, Mississauga, ON L5C 1V8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5716876,
        long: -79.6466141,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u529b\u5065\u8eabCPower Fitness Mississauga",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 451,
        cityName: "Mississauga",
        address: "3055 Vega Blvd, Mississauga, ON L5L 5Y3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5170749,
        long: -79.69028809999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 3.7,
        cityId: 7,
    },
    {
        gymId: 452,
        cityName: "Mississauga",
        address: "5077 Dixie Rd Bldg C, Mississauga, ON L4W 5S6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.637678,
        long: -79.6211716,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 4.4,
        cityId: 7,
    },
    {
        gymId: 453,
        cityName: "Mississauga",
        address: "6991 Millcreek Dr, Mississauga, ON L5N 6B9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.598097,
        long: -79.758714,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit4Less",
        rating: 4.4,
        cityId: 7,
    },
    {
        gymId: 454,
        cityName: "Mississauga",
        address: "5602 Tenth Line W, Mississauga, ON L5M 7L9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.55832,
        long: -79.7436364,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 3.8,
        cityId: 7,
    },
    {
        gymId: 455,
        cityName: "Mississauga",
        address: "3345 Laird Rd #3, Mississauga, ON L5L 5R6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5169988,
        long: -79.6920131,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "SkyFitness",
        rating: 4,
        cityId: 7,
    },
    {
        gymId: 456,
        cityName: "Mississauga",
        address: "1331 Crestlawn Dr Unit B, Mississauga, ON L4W 2P9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6332616,
        long: -79.6199432,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Strength-N-U | Fitness & Therapy",
        rating: 4.7,
        cityId: 7,
    },
    {
        gymId: 457,
        cityName: "Mississauga",
        address: "40 Annagem Blvd, Mississauga, ON L5T 2Y3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6355679,
        long: -79.69063419999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 4.1,
        cityId: 7,
    },
    {
        gymId: 458,
        cityName: "Mississauga",
        address: "2150 Burnhamthorpe Rd W, Mississauga, ON L5L 3A2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.54315380000001,
        long: -79.6831062,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Mississauga South Common Centre",
        rating: 3.6,
        cityId: 7,
    },
    {
        gymId: 459,
        cityName: "Mississauga",
        address: "1865 Lakeshore Rd W #13, Mississauga, ON L5J 4P1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5160671,
        long: -79.6261583,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "9Round Fitness",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 460,
        cityName: "Mississauga",
        address: "3090 Mavis Rd, Mississauga, ON L5C 1T8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5668301,
        long: -79.63684260000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Infitnity Fitness",
        rating: 4.3,
        cityId: 7,
    },
    {
        gymId: 461,
        cityName: "Mississauga",
        address: "60 Bristol Rd E, Mississauga, ON L4Z 3K8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.615142,
        long: -79.660637,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit4Less",
        rating: 4.1,
        cityId: 7,
    },
    {
        gymId: 462,
        cityName: "Mississauga",
        address: "5120 Dixie Rd Unit 12, Mississauga, ON L4W 4K2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6364034,
        long: -79.6229219,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "F45 Training Mississauga North",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 463,
        cityName: "Mississauga",
        address: "5757 Kennedy Rd #10, Mississauga, ON L4Z 0C5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.63110469999999,
        long: -79.66134989999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Training for Warriors Sauga | Personal Training Mississauga",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 464,
        cityName: "Mississauga",
        address: "100 City Centre Dr, Mississauga, ON L5B 2C9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.592752,
        long: -79.64301499999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Mississauga Square One",
        rating: 3,
        cityId: 7,
    },
    {
        gymId: 465,
        cityName: "Mississauga",
        address: "58 Oakwood Ave N, Mississauga, ON L5G 3L8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.56013799999999,
        long: -79.581722,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "CrossFit M3",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 466,
        cityName: "Mississauga",
        address: "4995 Timberlea Blvd Unit #6, Mississauga, ON L4W 2S2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6279437,
        long: -79.6356484,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "KONGA Fitness. Martial Arts. Therapy",
        rating: 4.9,
        cityId: 7,
    },
    {
        gymId: 467,
        cityName: "Mississauga",
        address: "6750 Mississauga Rd, Mississauga, ON L5N 2L3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6012596,
        long: -79.74341380000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Wynn Fitness Meadowvale",
        rating: 3.8,
        cityId: 7,
    },
    {
        gymId: 468,
        cityName: "Mississauga",
        address: "579 Lakeshore Rd E B, Mississauga, ON L5G 1H9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.56884360000001,
        long: -79.56970249999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Port Credit Athletics",
        rating: 4,
        cityId: 7,
    },
    {
        gymId: 469,
        cityName: "Mississauga",
        address: "128 Queen St S Unit 24, Mississauga, ON L5M 1K8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5832859,
        long: -79.71716479999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "F45 Training Streetsville",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 470,
        cityName: "Mississauga",
        address: "1215 Queensway E Unit 45, Mississauga, ON L4Y 3Y3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5999705,
        long: -79.5808234,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Ether Gym",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 471,
        cityName: "Mississauga",
        address: "1565 Britannia Rd E Unit 2, Mississauga, ON L4W 3C6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.65773979999999,
        long: -79.6474913,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Body By Chosen Mississauga",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 472,
        cityName: "Mississauga",
        address: "392 Gibraltar Dr, Mississauga, ON L5T 2P6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6517709,
        long: -79.6955012,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "C4 MMA & Fitness",
        rating: 4.6,
        cityId: 7,
    },
    {
        gymId: 473,
        cityName: "Mississauga",
        address: "6460 Millcreek Dr, Mississauga, ON L5N 2V6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5898253,
        long: -79.742795,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Crunch Fitness",
        rating: 3,
        cityId: 7,
    },
    {
        gymId: 474,
        cityName: "Mississauga",
        address: "1150 Lorne Park Rd, Mississauga, ON L5H 3A7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5305386,
        long: -79.61603900000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 3,
        cityId: 7,
    },
    {
        gymId: 475,
        cityName: "Mississauga",
        address: "3900 Grand Park Dr, Mississauga, ON L5B 4M6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.57902600000001,
        long: -79.6471656,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "UFC GYM Mississauga",
        rating: 3.6,
        cityId: 7,
    },
    {
        gymId: 476,
        cityName: "Mississauga",
        address: "325 Burnhamthorpe Rd W, Mississauga, ON L5B 3R2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.58694879999999,
        long: -79.64450880000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Mississauga YMCA",
        rating: 3.7,
        cityId: 7,
    },
    {
        gymId: 477,
        cityName: "Mississauga",
        address: "66 Thomas Street #32 & 34, Mississauga, ON L5M 2P3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5778878,
        long: -79.7156234,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "TERNION Fitness & Athletics",
        rating: 5,
        cityId: 7,
    },
    {
        gymId: 478,
        cityName: "Mississauga",
        address: "225 Traders Blvd E, Mississauga, ON L4Z 3L8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6281297,
        long: -79.6691037,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Progressive Health & Fitness",
        rating: 4.9,
        cityId: 7,
    },
    {
        gymId: 479,
        cityName: "Mississauga",
        address: "3420 Semenyk Ct #2, Mississauga, ON L5C 4P8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.5673804,
        long: -79.65217620000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Athletic Leaders",
        rating: 4.9,
        cityId: 7,
    },
    {
        gymId: 480,
        cityName: "Mississauga",
        address: "5200 Dixie road Unit 7, Mississauga, ON L4W 1E4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6396995,
        long: -79.6269456,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Lean Body Studio - Mississauga",
        rating: 4.6,
        cityId: 7,
    },
];
