import { GymCreationAttributes } from "../../database/models/Gym";

export const MontrealGymSeed = [
    {
        gymId: 121,
        cityName: "Montreal",
        address: "8770 Boul Langelier, Montr\u00e9al, QC H1P 3C6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.599659,
        long: -73.5940569,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Pro Gym",
        rating: 4.5,
        cityId: 6,
    },
    {
        gymId: 122,
        cityName: "Montreal",
        address: "4117 St Laurent Blvd, Montreal, Quebec H2W 1Y7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5176255,
        long: -73.5805108,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.4,
        cityId: 6,
    },
    {
        gymId: 123,
        cityName: "Montreal",
        address: "1688 Mont-Royal Ave E, Montreal, Quebec H2J 1Z5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5325484,
        long: -73.57471810000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Gym du Plateau",
        rating: 4.6,
        cityId: 6,
    },
    {
        gymId: 124,
        cityName: "Montreal",
        address: "1100 Rue Sherbrooke O Suite 300, Montr\u00e9al, QC H3A 1G7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5016128,
        long: -73.5765112,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Club Athletique Sherbrooke",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 125,
        cityName: "Montreal",
        address: "5733 Sherbrooke St W, Montreal, Quebec H4A 1W9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4706093,
        long: -73.616134,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Dogym",
        rating: 4.6,
        cityId: 6,
    },
    {
        gymId: 126,
        cityName: "Montreal",
        address: "4850 St Ambroise St suite #100, Montreal, Quebec H4C 3N8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4692888,
        long: -73.5872444,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Crossfit Montreal",
        rating: 4.7,
        cityId: 6,
    },
    {
        gymId: 127,
        cityName: "Montreal",
        address: "1001 Rue Lenoir Suite A-120, Montreal, Quebec H4C 2Z6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.476593,
        long: -73.591927,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "B52",
        rating: 4.7,
        cityId: 6,
    },
    {
        gymId: 128,
        cityName: "Montreal",
        address: "1050 Sherbrooke St W, Montreal, Quebec H3A 2R6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5020663,
        long: -73.5760159,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Club Sportif MAA",
        rating: 4.5,
        cityId: 6,
    },
    {
        gymId: 129,
        cityName: "Montreal",
        address: "8170 Decarie Blvd, Montreal, Quebec H4P 2S8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4982728,
        long: -73.6609789,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Siscoe Gym",
        rating: 4.5,
        cityId: 6,
    },
    {
        gymId: 130,
        cityName: "Montreal",
        address: "385 Mayor St, Montreal, Quebec H3A 2K5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5063938,
        long: -73.5688649,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Studio EPIX Montreal Centre-Ville / BootCamp Urbain",
        rating: 4.8,
        cityId: 6,
    },
    {
        gymId: 131,
        cityName: "Montreal",
        address: "4330 Rue Saint-Jacques, Montr\u00e9al, QC H4C 1J6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4764811,
        long: -73.5885658,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Gym St-Henri",
        rating: 4.2,
        cityId: 6,
    },
    {
        gymId: 132,
        cityName: "Montreal",
        address: "279 Rue Sherbrooke O #315, Montr\u00e9al, QC H2X 1Y2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5088324,
        long: -73.571382,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Rgym",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 133,
        cityName: "Montreal",
        address: "237 Av. Laurier O Suite C1, Montreal, Quebec H2T 2N9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.52049239999999,
        long: -73.595311,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.4,
        cityId: 6,
    },
    {
        gymId: 134,
        cityName: "Montreal",
        address: "5524 Rue Saint-Patrick #150, Montr\u00e9al, QC H4E 1A8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4636898,
        long: -73.5948435,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Canal Fitness",
        rating: 4.6,
        cityId: 6,
    },
    {
        gymId: 135,
        cityName: "Montreal",
        address: "1972 Saint-Catherine St W, Montreal, Quebec H3H 1M4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4920422,
        long: -73.5811015,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Report Fitness",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 136,
        cityName: "Montreal",
        address: "1620 Notre-Dame St W, Montreal, Quebec H3J 1M1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4895646,
        long: -73.567362,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Blackout Fitness",
        rating: 4.7,
        cityId: 6,
    },
    {
        gymId: 137,
        cityName: "Montreal",
        address: "6105 Av. du Bois\u00e9, Montr\u00e9al, QC H3S 2V9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5112229,
        long: -73.6214176,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Midtown Le Sporting Club Sanctuaire",
        rating: 4,
        cityId: 6,
    },
    {
        gymId: 138,
        cityName: "Montreal",
        address: "1056 Ottawa St, Montreal, Quebec H3C 0T8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.494307,
        long: -73.55899579999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.8,
        cityId: 6,
    },
    {
        gymId: 139,
        cityName: "Montreal",
        address: "3720 Ave Van Horne, Montreal, Quebec H3S 1R8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.500431,
        long: -73.63225299999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness",
        rating: 3.9,
        cityId: 6,
    },
    {
        gymId: 140,
        cityName: "Montreal",
        address: "1431 St Andre St, Montreal, Quebec H2L 3T3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5167572,
        long: -73.5585387,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Nautilus Plus Downtown East",
        rating: 4.2,
        cityId: 6,
    },
    {
        gymId: 141,
        cityName: "Montreal",
        address: "3645 Notre-Dame St W, Montreal, Quebec H4C 1P6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 45.47950650000001,
        long: -73.5813857,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "Hard Knox Gym",
        rating: 4.6,
        cityId: 6,
    },
    {
        gymId: 142,
        cityName: "Montreal",
        address: "EV S2, 1515 Sainte-Catherine O #206, Montr\u00e9al, QC H3G 2W1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4953688,
        long: -73.5779964,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Le Gym Concordia",
        rating: 3.9,
        cityId: 6,
    },
    {
        gymId: 143,
        cityName: "Montreal",
        address: "5275 Ferrier St Suite 306, Montreal, Quebec H4P 1L7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4981778,
        long: -73.6572431,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Gym Imperial Fitness",
        rating: 5,
        cityId: 6,
    },
    {
        gymId: 144,
        cityName: "Montreal",
        address: "156 Ronald Dr, Montreal West, Quebec H4X 1M8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4488136,
        long: -73.64153569999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "909 Gym",
        rating: 5,
        cityId: 6,
    },
    {
        gymId: 145,
        cityName: "Montreal",
        address: "507 Place d'Armes Basement, Montreal, Quebec H2Y 2W8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5051378,
        long: -73.55670769999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "U.N.I. Training Vieux Montreal",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 146,
        cityName: "Montreal",
        address: "3333 Rue Jarry E #200, Montr\u00e9al, QC H1Z 2E5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.56492799999999,
        long: -73.609549,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness au f\u00e9minin",
        rating: 4.1,
        cityId: 6,
    },
    {
        gymId: 147,
        cityName: "Montreal",
        address: "360 Rue Saint-Jacques, Montr\u00e9al, QC H2Y 2N1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5023158,
        long: -73.5593476,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Vsquare Fitness",
        rating: 4.7,
        cityId: 6,
    },
    {
        gymId: 148,
        cityName: "Montreal",
        address: "5000 Rue Jean-Talon O Suite 110, Montreal, Quebec H4P 1W9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4961257,
        long: -73.649248,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "SWEAT440 Montreal",
        rating: 4.8,
        cityId: 6,
    },
    {
        gymId: 149,
        cityName: "Montreal",
        address: "3505 Atwater Ave, Montreal, Quebec H3H 1Y2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4926586,
        long: -73.58944490000002,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Club Atwater",
        rating: 4.6,
        cityId: 6,
    },
    {
        gymId: 150,
        cityName: "Montreal",
        address: "625 Saint-Catherine St W Suite 1260, Montreal, Quebec H3B 1B7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.502666,
        long: -73.5714289,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness",
        rating: 3.6,
        cityId: 6,
    },
    {
        gymId: 151,
        cityName: "Montreal",
        address: "1 Pl. Monseigneur Charbonneau, Montreal, Quebec H3B 4M7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5012882,
        long: -73.5687429,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Nautilus Plus",
        rating: 4,
        cityId: 6,
    },
    {
        gymId: 152,
        cityName: "Montreal",
        address: "2175 Mont-Royal Ave E, Montreal, Quebec H2H 1K2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.536269,
        long: -73.571739,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness 24/7",
        rating: 3.9,
        cityId: 6,
    },
    {
        gymId: 153,
        cityName: "Montreal",
        address: "8255 Bd Saint-Michel, Montr\u00e9al, QC H1Z 3E4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.565044,
        long: -73.611385,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness 24/7",
        rating: 3.9,
        cityId: 6,
    },
    {
        gymId: 154,
        cityName: "Montreal",
        address: "987 de la Commune St W, Montreal, Quebec H3C 4H5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.493241,
        long: -73.5536492,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "De la Commune outdoor gym",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 155,
        cityName: "Montreal",
        address: "55 Ave des Pins, Montreal, Quebec H2W 1N6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.515773,
        long: -73.5746671,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness 24/7",
        rating: 3.8,
        cityId: 6,
    },
    {
        gymId: 156,
        cityName: "Montreal",
        address: "20 Boul Cr\u00e9mazie E, Montr\u00e9al, QC H2P 1C8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.542183,
        long: -73.64061,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness Extra",
        rating: 3.9,
        cityId: 6,
    },
    {
        gymId: 157,
        cityName: "Montreal",
        address: "828 St Catherine St E, Montreal, Quebec H2L 2E2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.515572,
        long: -73.55839399999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness 24/7",
        rating: 3.7,
        cityId: 6,
    },
    {
        gymId: 158,
        cityName: "Montreal",
        address: "4535 Av. Papineau, Montr\u00e9al, QC H2H 1V4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.533451,
        long: -73.575321,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9nergie Cardio Plateau Mont-Royal",
        rating: 4.4,
        cityId: 6,
    },
    {
        gymId: 159,
        cityName: "Montreal",
        address: "1345 Rue de Bellechasse, Montr\u00e9al, QC H2G 1N8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.53903570000001,
        long: -73.5961327,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Halteres&Go",
        rating: 4.8,
        cityId: 6,
    },
    {
        gymId: 160,
        cityName: "Montreal",
        address: "2221 Rue Pitt, Montr\u00e9al, QC H4E 1A2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.469469,
        long: -73.5805792,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Crossfit PRO1 Montreal",
        rating: 5,
        cityId: 6,
    },
    {
        gymId: 161,
        cityName: "Montreal",
        address: "5275 Ferrier St, Montreal, Quebec H4P 1L7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4982552,
        long: -73.6576563,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Tristar Gym",
        rating: 4.6,
        cityId: 6,
    },
    {
        gymId: 162,
        cityName: "Montreal",
        address: "12075 Blvd. Laurentien, Montreal, Quebec H4K 1N3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.527179,
        long: -73.7172734,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "UNICITYGYM 24h",
        rating: 5,
        cityId: 6,
    },
    {
        gymId: 163,
        cityName: "Montreal",
        address: "6700 Ch. de la C\u00f4te-des-Neiges Local 184, Montreal, Quebec H3S 2B2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.502681,
        long: -73.6376751,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness",
        rating: 3.5,
        cityId: 6,
    },
    {
        gymId: 164,
        cityName: "Montreal",
        address: "651 Rue Bridge, Montr\u00e9al, QC H3K 2C8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4875376,
        long: -73.5584001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "CrossFit Wonderland",
        rating: 4.7,
        cityId: 6,
    },
    {
        gymId: 165,
        cityName: "Montreal",
        address: "137 Rue Saint-Ferdinand #122, Montreal, Quebec H4C 2S6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4750597,
        long: -73.58225399999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Gym OPEX Montr\u00e9al - Personal Trainer - Crossfit",
        rating: 4.8,
        cityId: 6,
    },
    {
        gymId: 166,
        cityName: "Montreal",
        address: "2574 Centre St, Montreal, Quebec H3K 1J8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4785031,
        long: -73.5690384,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "30 Minute Hit",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 167,
        cityName: "Montreal",
        address: "8490 Rue Jeanne-Mance #104, Montr\u00e9al, QC H2P 2S3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        lat: 45.5353114,
        long: -73.64037979999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
        name: "Le vestiaire gym",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 168,
        cityName: "Montreal",
        address: "3863 St Laurent Blvd studio 201, Montreal, Quebec H2W 1Y1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5161379,
        long: -73.57725769999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Entra\u00eenement X-Fit Saint-Laurent",
        rating: 4.8,
        cityId: 6,
    },
    {
        gymId: 169,
        cityName: "Montreal",
        address: "55 Mont-Royal Ave W, Montreal, Quebec H2T 2S6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5193626,
        long: -73.5872179,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Nautilus Plus Plateau",
        rating: 3.9,
        cityId: 6,
    },
    {
        gymId: 170,
        cityName: "Montreal",
        address: "7735 Bd Maurice-Duplessis, Montr\u00e9al, QC H1E 1M5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.628769,
        long: -73.594208,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness 24/7",
        rating: 4.1,
        cityId: 6,
    },
    {
        gymId: 171,
        cityName: "Montreal",
        address: "4325 Saint Denis St, Montreal, Quebec H2J 2K9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.52283070000001,
        long: -73.5799993,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "RepFit Plateau",
        rating: 4.7,
        cityId: 6,
    },
    {
        gymId: 172,
        cityName: "Montreal",
        address: "1150 Wellington St, Montreal, Quebec H3C 1V8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4923358,
        long: -73.55786839999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "World Gym Griffintown",
        rating: 3.7,
        cityId: 6,
    },
    {
        gymId: 173,
        cityName: "Montreal",
        address: "5381 St Laurent Blvd, Montreal, Quebec H2T 1S5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.52506899999999,
        long: -73.5969315,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Elite Coaching - The private training gym Mile End",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 174,
        cityName: "Montreal",
        address: "1001 Av. Rockland, Outremont, QC H2V 3A3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5186871,
        long: -73.6213154,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Chau Fitness",
        rating: 5,
        cityId: 6,
    },
    {
        gymId: 175,
        cityName: "Montreal",
        address: "3500 Blvd. Cote-Vertu Ouest, Saint-Laurent, Quebec H4R 2X7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.493878,
        long: -73.7050939,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness 24/7",
        rating: 4.2,
        cityId: 6,
    },
    {
        gymId: 176,
        cityName: "Montreal",
        address: "3575 Park Ave, Montreal, Quebec H2X 3P9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5103141,
        long: -73.5751317,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Club LaCit\u00e9",
        rating: 3.6,
        cityId: 6,
    },
    {
        gymId: 177,
        cityName: "Montreal",
        address: "2101 Trans Canada Route, Dorval, Quebec H9P 1J1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.4838449,
        long: -73.7868392,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Monster Gym",
        rating: 4.4,
        cityId: 6,
    },
    {
        gymId: 178,
        cityName: "Montreal",
        address: "800 Rue du Square-Victoria, Montr\u00e9al, QC H4Z 1A1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5003412,
        long: -73.5620714,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Nautilus Plus Victoria Square",
        rating: 3.6,
        cityId: 6,
    },
    {
        gymId: 179,
        cityName: "Montreal",
        address: "1500 Atwater Ave, Montreal, Quebec H3Z 1X5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.488805,
        long: -73.58599199999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "\u00c9conofitness 24/7",
        rating: 3.3,
        cityId: 6,
    },
    {
        gymId: 180,
        cityName: "Montreal",
        address: "2237 Rue Larivi\u00e8re, Montr\u00e9al, QC H2K 1P6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5307228,
        long: -73.5578254,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Focusgyms - Gym priv\u00e9",
        rating: 5,
        cityId: 6,
    },
    {
        gymId: 641,
        cityName: "Montreal",
        address: "9210 Bd Maurice-Duplessis, Montr\u00e9al, QC H1E 1M7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.64667540000001,
        long: -73.56847189999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Gym Fit Forme",
        rating: 4.5,
        cityId: 6,
    },
    {
        gymId: 642,
        cityName: "Montreal",
        address: "153 Rue Beaubien O, Montr\u00e9al, QC H2V 1C4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5286612,
        long: -73.6115191,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Crossfit Waverly",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 647,
        cityName: "Montreal",
        address: "3988 Saint Denis St, Montreal, Quebec H2W 2M2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5204048,
        long: -73.5755233,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Espace Thomas",
        rating: 4.3,
        cityId: 6,
    },
    {
        gymId: 651,
        cityName: "Montreal",
        address: "5555 Av. de Gasp\u00e9, Montr\u00e9al, QC H2T 2A3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5278614,
        long: -73.59766119999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "L'\u00c9CURIE, centre d'entra\u00eenement",
        rating: 5,
        cityId: 6,
    },
    {
        gymId: 656,
        cityName: "Montreal",
        address: "220 Bd Cr\u00e9mazie O, Montr\u00e9al, QC H2P 1C6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5385897,
        long: -73.6430173,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Biner Training",
        rating: 4.9,
        cityId: 6,
    },
    {
        gymId: 659,
        cityName: "Montreal",
        address: "2600 Rue William-Tremblay #133, Montr\u00e9al, QC H1Y 3J2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 45.5432001,
        long: -73.5635465,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Locomotion Studio",
        rating: 4.8,
        cityId: 6,
    },
];
