import { GymCreationAttributes } from "../../database/models/Gym";

export const Toronto = [
    {
        gymId: 301,
        cityName: "Toronto",
        address: "373 King St W, Toronto, ON M5V 1K1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6457101,
        long: -79.39290369999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit Factory Downtown",
        rating: 4.7,
        cityId: 5,
    },
    {
        gymId: 302,
        cityName: "Toronto",
        address: "2100 Bloor St W, Toronto, ON M6S 1M7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6524079,
        long: -79.4711535,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "CONQUER FITNESS",
        rating: 4.8,
        cityId: 5,
    },
    {
        gymId: 303,
        cityName: "Toronto",
        address: "267 Richmond St W, Toronto, ON M5V 3M6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.648754,
        long: -79.39193999999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Richmond and John",
        rating: 4.4,
        cityId: 5,
    },
    {
        gymId: 304,
        cityName: "Toronto",
        address: "390 Queens Quay W Unit 112, Toronto, ON M5V 3A6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6384582,
        long: -79.3906374,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "416 Fitness Club",
        rating: 4.8,
        cityId: 5,
    },
    {
        gymId: 305,
        cityName: "Toronto",
        address: "1 York St 5th Floor, Toronto, ON M5J 0B6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6416001,
        long: -79.3802103,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Pure Fitness Canada York Street",
        rating: 4.2,
        cityId: 5,
    },
    {
        gymId: 306,
        cityName: "Toronto",
        address: "620 Church St, Toronto, ON M4Y 2G2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.668775,
        long: -79.3825435,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Lyft Fitness",
        rating: 4.8,
        cityId: 5,
    },
    {
        gymId: 307,
        cityName: "Toronto",
        address: "505 Dupont St, Toronto, ON M6G 1Y6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6724665,
        long: -79.4160251,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Vive Fitness 24/7 Dupont Toronto",
        rating: 4.5,
        cityId: 5,
    },
    {
        gymId: 308,
        cityName: "Toronto",
        address: "137 Yonge St, Toronto, ON M5C 1W6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.651242,
        long: -79.378068,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto 137 Yonge Street",
        rating: 4,
        cityId: 5,
    },
    {
        gymId: 309,
        cityName: "Toronto",
        address: "First Canadian Place, 1, Toronto, ON M5X 1C8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6493546,
        long: -79.3819558,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Adelaide Club",
        rating: 4.6,
        cityId: 5,
    },
    {
        gymId: 310,
        cityName: "Toronto",
        address: "7 Hart House Cir, Toronto, ON M5S 3H3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6640232,
        long: -79.3952043,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Hart House Fitness Centre",
        rating: 4.4,
        cityId: 5,
    },
    {
        gymId: 311,
        cityName: "Toronto",
        address: "30 Weston Rd Suite 207, Toronto, ON M6N 0A7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6727103,
        long: -79.46814669999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.1,
        cityId: 5,
    },
    {
        gymId: 312,
        cityName: "Toronto",
        address: "7 Isabella St, Toronto, ON M4Y 1M7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6675629,
        long: -79.38516840000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Hone Fitness",
        rating: 4.2,
        cityId: 5,
    },
    {
        gymId: 313,
        cityName: "Toronto",
        address: "234 Front St E, Toronto, ON M5A 1G1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6512563,
        long: -79.36471879999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Body + Soul Fitness",
        rating: 4.6,
        cityId: 5,
    },
    {
        gymId: 314,
        cityName: "Toronto",
        address: "80 Bloor St W, Toronto, ON M5S 2V1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.669863,
        long: -79.390176,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Bloor and Bay",
        rating: 3.9,
        cityId: 5,
    },
    {
        gymId: 315,
        cityName: "Toronto",
        address: "12 St Clair Ave E, Toronto, ON M4T 1L7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.688484,
        long: -79.39378099999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Yonge and St Clair",
        rating: 4.1,
        cityId: 5,
    },
    {
        gymId: 316,
        cityName: "Toronto",
        address: "199 Bay St., Toronto, ON M5L 1E2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6480874,
        long: -79.379662,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Equinox Bay Street",
        rating: 3.9,
        cityId: 5,
    },
    {
        gymId: 317,
        cityName: "Toronto",
        address: "555 Richmond St W, Toronto, ON M5V 3B1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.646365,
        long: -79.402312,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Richmond and Bathurst",
        rating: 4,
        cityId: 5,
    },
    {
        gymId: 318,
        cityName: "Toronto",
        address: "807 Bathurst St, Toronto, ON M5R 3G2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6656615,
        long: -79.41119549999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Vive Fitness 24/7 Bathurst Toronto",
        rating: 4.5,
        cityId: 5,
    },
    {
        gymId: 319,
        cityName: "Toronto",
        address: "209 Adelaide St E, Toronto, ON M5A 1M8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6513696,
        long: -79.3716351,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "6S Fitness+",
        rating: 4.9,
        cityId: 5,
    },
    {
        gymId: 320,
        cityName: "Toronto",
        address: "7 Station St, Toronto, ON M5J 1C3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.644336,
        long: -79.383625,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Union Station",
        rating: 3.8,
        cityId: 5,
    },
    {
        gymId: 321,
        cityName: "Toronto",
        address: "276 Carlaw Ave #101, Toronto, ON M4M 3L1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.663475,
        long: -79.3413467,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Dwell Gym",
        rating: 4.7,
        cityId: 5,
    },
    {
        gymId: 322,
        cityName: "Toronto",
        address: "488 Parliament St, Toronto, ON M4X 1P2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.664822,
        long: -79.3683708,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Parliament Street Fitness",
        rating: 4.9,
        cityId: 5,
    },
    {
        gymId: 323,
        cityName: "Toronto",
        address: "600 Fleet St, Toronto, ON M5V 1B7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.63666810000001,
        long: -79.4004451,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.9,
        cityId: 5,
    },
    {
        gymId: 324,
        cityName: "Toronto",
        address: "2300 Yonge St, Toronto, ON M4P 1E4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.707276,
        long: -79.399562,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Yonge Eglinton Centre",
        rating: 3.9,
        cityId: 5,
    },
    {
        gymId: 325,
        cityName: "Toronto",
        address: "110 Eglinton Ave E, Toronto, ON M4P 1A6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.707645,
        long: -79.395303,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Dunfield and Eglinton",
        rating: 4,
        cityId: 5,
    },
    {
        gymId: 326,
        cityName: "Toronto",
        address: "250 Davisville Ave, Toronto, ON M4S 2L9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.700802,
        long: -79.386417,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Mount Pleasant and Davisville",
        rating: 4,
        cityId: 5,
    },
    {
        gymId: 327,
        cityName: "Toronto",
        address: "196 Spadina Ave., Toronto, ON M5T 2C2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6501709,
        long: -79.3974004,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Hone Fitness Queen & Spadina",
        rating: 4.2,
        cityId: 5,
    },
    {
        gymId: 328,
        cityName: "Toronto",
        address: "320 Richmond St E Unit 104, Toronto, ON M5A 2P9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6535976,
        long: -79.3687461,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "9Round Fitness",
        rating: 4.7,
        cityId: 5,
    },
    {
        gymId: 329,
        cityName: "Toronto",
        address: "460 Richmond St W Suite 100, Toronto, ON M5V 1Y1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6479085,
        long: -79.3977184,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Arzadon Fitness",
        rating: 5,
        cityId: 5,
    },
    {
        gymId: 330,
        cityName: "Toronto",
        address: "483 Bay St., Toronto, ON M5G 2C9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.653436,
        long: -79.382314,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Bell Trinity Centre",
        rating: 4,
        cityId: 5,
    },
    {
        gymId: 331,
        cityName: "Toronto",
        address: "1083 Dundas St W, Toronto, ON M6J 1W9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6494314,
        long: -79.41883899999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Academy of Lions",
        rating: 4.5,
        cityId: 5,
    },
    {
        gymId: 332,
        cityName: "Toronto",
        address: "161 Eglinton Ave E, Toronto, ON M4P 1J5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7077401,
        long: -79.39244769999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit Factory Midtown",
        rating: 4.8,
        cityId: 5,
    },
    {
        gymId: 333,
        cityName: "Toronto",
        address: "580 King St W #2, Toronto, ON M5V 1M1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.644876,
        long: -79.39938959999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Elle Fitness and Social",
        rating: 4.5,
        cityId: 5,
    },
    {
        gymId: 334,
        cityName: "Toronto",
        address: "43 Junction Rd, Toronto, ON M6N 1B5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6675237,
        long: -79.4637965,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 4,
        cityId: 5,
    },
    {
        gymId: 335,
        cityName: "Toronto",
        address: "20 Brentcliffe Rd #4, Toronto, ON M4G 0C6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.713012,
        long: -79.3600768,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Pure Fitness Canada Eglinton",
        rating: 4.2,
        cityId: 5,
    },
    {
        gymId: 336,
        cityName: "Toronto",
        address: "230 Nantucket Blvd #1, Scarborough, ON M1P 2N9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7592474,
        long: -79.27591,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Afterburn Fitness",
        rating: 5,
        cityId: 5,
    },
    {
        gymId: 337,
        cityName: "Toronto",
        address: "1866 Queen St E, Toronto, ON M4L 1H2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.668675,
        long: -79.3066584,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "9Round Fitness",
        rating: 5,
        cityId: 5,
    },
    {
        gymId: 338,
        cityName: "Toronto",
        address: "165 King St W, Toronto, ON M5H 4H2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.647465,
        long: -79.38525419999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "F45 Training Toronto Downtown",
        rating: 4.8,
        cityId: 5,
    },
    {
        gymId: 339,
        cityName: "Toronto",
        address: "40 University Ave, Toronto, ON M5J 1T1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.646103,
        long: -79.3844269,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.8,
        cityId: 5,
    },
    {
        gymId: 340,
        cityName: "Toronto",
        address: "388 Carlaw Ave w3, Toronto, ON M4M 2T4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6655712,
        long: -79.3429146,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Primal Gym",
        rating: 4.9,
        cityId: 5,
    },
    {
        gymId: 341,
        cityName: "Toronto",
        address: "777 Bay St. M219, Toronto, ON M7A 2J3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6606226,
        long: -79.3841909,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "9Round Fitness",
        rating: 4.8,
        cityId: 5,
    },
    {
        gymId: 342,
        cityName: "Toronto",
        address: "100 Devonshire Pl, Toronto, ON M5S 2C9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6668989,
        long: -79.3982204,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Goldring Centre for High Performance Sport",
        rating: 4.6,
        cityId: 5,
    },
    {
        gymId: 343,
        cityName: "Toronto",
        address: "4861 Yonge St, Toronto, ON M2N 5X2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.762123,
        long: -79.4107262,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 4.1,
        cityId: 5,
    },
    {
        gymId: 344,
        cityName: "Toronto",
        address: "11 Carlaw Ave #1, Toronto, ON M4M 2R6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.656399,
        long: -79.3368467,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fortis Fitness",
        rating: 4.7,
        cityId: 5,
    },
    {
        gymId: 345,
        cityName: "Toronto",
        address: "85 Hanna Ave, Toronto, ON M6K 3S3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.64006,
        long: -79.419812,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto King Liberty",
        rating: 3.9,
        cityId: 5,
    },
    {
        gymId: 346,
        cityName: "Toronto",
        address: "175 Avenue Rd, Toronto, ON M5R 2J2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6749677,
        long: -79.3964022,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "646 Weightlifting Gym",
        rating: 4.8,
        cityId: 5,
    },
    {
        gymId: 347,
        cityName: "Toronto",
        address: "181 Wellington St W, Toronto, ON M5J 2H5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6453284,
        long: -79.3871147,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Innovative Fitness Toronto (Ritz-Carlton)",
        rating: 5,
        cityId: 5,
    },
    {
        gymId: 348,
        cityName: "Toronto",
        address: "1000 Gerrard St E, Toronto, ON M4M 3G6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.668828,
        long: -79.33927539999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Planet Fitness",
        rating: 4,
        cityId: 5,
    },
    {
        gymId: 349,
        cityName: "Toronto",
        address: "97 Eglinton Ave E, Toronto, ON M4P 1H4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.70721959999999,
        long: -79.394964,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.5,
        cityId: 5,
    },
    {
        gymId: 350,
        cityName: "Toronto",
        address: "324 Lonsdale Rd, Toronto, ON M4V 1X4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6888304,
        long: -79.4123304,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Forest Hill Village Gym",
        rating: 5,
        cityId: 5,
    },
    {
        gymId: 351,
        cityName: "Toronto",
        address: "33 Davisville Ave, Toronto, ON M4S 2Y9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6984932,
        long: -79.3947991,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Striation 6 Fitness Centre",
        rating: 4.6,
        cityId: 5,
    },
    {
        gymId: 352,
        cityName: "Toronto",
        address: "8 Park Rd, Toronto, ON M4W 3G8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.671302,
        long: -79.38469099999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Toronto Bloor and Park",
        rating: 3.7,
        cityId: 5,
    },
    {
        gymId: 353,
        cityName: "Toronto",
        address: "1245 Dupont St, Toronto, ON M6H 2A6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6673622,
        long: -79.4428606,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Planet Fitness",
        rating: 3.9,
        cityId: 5,
    },
    {
        gymId: 354,
        cityName: "Toronto",
        address: "1312 King St W, Toronto, ON M6K 1G8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6382116,
        long: -79.4315167,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Body By Chosen Toronto",
        rating: 4.7,
        cityId: 5,
    },
    {
        gymId: 355,
        cityName: "Toronto",
        address: "1380 Don Mills Rd., Toronto, ON M3B 2X2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.7475643,
        long: -79.34701299999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "LA Fitness",
        rating: 4.2,
        cityId: 5,
    },
    {
        gymId: 356,
        cityName: "Toronto",
        address: "8 Church St, Toronto, ON M5E 1M1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6476068,
        long: -79.3735833,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "MedX Precision Fitness",
        rating: 4.9,
        cityId: 5,
    },
    {
        gymId: 357,
        cityName: "Toronto",
        address: "687 St Clair Ave W, Toronto, ON M6C 1B2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6813999,
        long: -79.42581249999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "9Round Fitness",
        rating: 5,
        cityId: 5,
    },
    {
        gymId: 358,
        cityName: "Toronto",
        address: "56 Colborne St, Toronto, ON M5E 1E3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6492276,
        long: -79.3746943,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Altitude Athletic Training",
        rating: 5,
        cityId: 5,
    },
    {
        gymId: 359,
        cityName: "Toronto",
        address: "995 Pape Ave, Rear Unit, East York, ON M4K 3V8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.68776940000001,
        long: -79.3478308,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Quantum Strength & Fitness",
        rating: 5,
        cityId: 5,
    },
    {
        gymId: 360,
        cityName: "Toronto",
        address: "1605 Bloor St W, Toronto, ON M6P 1A6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 43.6555496,
        long: -79.4550845,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Soul Fuel Fitness",
        rating: 5,
        cityId: 5,
    },
];
