import { GymCreationAttributes } from "../../database/models/Gym";

export const Vancouver = [
    {
        gymId: 181,
        cityName: "Vancouver",
        address: "709 W Broadway, Vancouver, BC V5Z 1J5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2634378,
        long: -123.1202924,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Gold's Gym West Broadway",
        rating: 4.2,
        cityId: 1,
    },
    {
        gymId: 182,
        cityName: "Vancouver",
        address: "1449 Hornby St, Vancouver, BC V6Z 1W8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.27586669999999,
        long: -123.1323712,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Dynasty Gym/CrossFit Palace",
        rating: 4.9,
        cityId: 1,
    },
    {
        gymId: 183,
        cityName: "Vancouver",
        address: "1433 Cedar Cottage Mews, Vancouver, BC V5N 5Z2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.24928569999999,
        long: -123.0749596,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.6,
        cityId: 1,
    },
    {
        gymId: 184,
        cityName: "Vancouver",
        address: "489 W 2nd Ave, Vancouver, BC V5Y 1E3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2671698,
        long: -123.1140993,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.5,
        cityId: 1,
    },
    {
        gymId: 185,
        cityName: "Vancouver",
        address: "1214 Howe St, Vancouver, BC V6Z 1R5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2775605,
        long: -123.1273321,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fitness World",
        rating: 4.3,
        cityId: 1,
    },
    {
        gymId: 186,
        cityName: "Vancouver",
        address: "1522 Commercial Dr, Vancouver, BC V5L 3Y2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2710296,
        long: -123.0692036,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Spartacus Gym",
        rating: 4.3,
        cityId: 1,
    },
    {
        gymId: 187,
        cityName: "Vancouver",
        address: "1131 W Georgia St, Vancouver, BC V6E 4G2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2862731,
        long: -123.1235959,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Equinox West Georgia Street",
        rating: 4.1,
        cityId: 1,
    },
    {
        gymId: 188,
        cityName: "Vancouver",
        address: "of the One Pacific Building, 60 Smithe St 2nd Floor, Vancouver, BC V6B 0B5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2750215,
        long: -123.1141977,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.5,
        cityId: 1,
    },
    {
        gymId: 189,
        cityName: "Vancouver",
        address: "1015 Denman St #200, Vancouver, BC V6G 2M4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2892759,
        long: -123.1392316,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness Denman",
        rating: 4.3,
        cityId: 1,
    },
    {
        gymId: 190,
        cityName: "Vancouver",
        address: "1661 Napier St, Vancouver, BC V5L 2K6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2756576,
        long: -123.0706252,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Britannia Fitness Centre",
        rating: 4.1,
        cityId: 1,
    },
    {
        gymId: 191,
        cityName: "Vancouver",
        address: "1160 Davie St #105, Vancouver, BC V6E 1N1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2809707,
        long: -123.1323721,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.5,
        cityId: 1,
    },
    {
        gymId: 192,
        cityName: "Vancouver",
        address: "535 Hornby St, Vancouver, BC V6C 2E8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2855157,
        long: -123.1178076,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "YWCA Health + Fitness Centre",
        rating: 4.6,
        cityId: 1,
    },
    {
        gymId: 193,
        cityName: "Vancouver",
        address: "788 Beatty St Unit B2, Vancouver, BC V6B 2M1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2775995,
        long: -123.1134834,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Function Health Club Downtown Vancouver",
        rating: 4.8,
        cityId: 1,
    },
    {
        gymId: 194,
        cityName: "Vancouver",
        address: "2892 Cambie St #4, Vancouver, BC V5Z 2V5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2595924,
        long: -123.1147752,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.4,
        cityId: 1,
    },
    {
        gymId: 195,
        cityName: "Vancouver",
        address: "Sun Tower, 128 W Pender St #102, Vancouver, BC V6B 1R8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2811087,
        long: -123.1084153,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Kalev Fitness Solution",
        rating: 4.7,
        cityId: 1,
    },
    {
        gymId: 196,
        cityName: "Vancouver",
        address: "1201 W Pender St W Unit #100, Vancouver, BC V6E 2V2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.28875,
        long: -123.123398,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit4Less",
        rating: 3.9,
        cityId: 1,
    },
    {
        gymId: 197,
        cityName: "Vancouver",
        address: "1035 W Pender St, Vancouver, BC V6C 3R2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2873199,
        long: -123.1191328,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Barry's Vancouver",
        rating: 4.8,
        cityId: 1,
    },
    {
        gymId: 198,
        cityName: "Vancouver",
        address: "909 W Broadway, Vancouver, BC V5Z 1J3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2635397,
        long: -123.1246775,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Gymbox",
        rating: 4.3,
        cityId: 1,
    },
    {
        gymId: 199,
        cityName: "Vancouver",
        address: "1055 Canada Pl Unit 50, Vancouver, BC V6C 0C3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2895457,
        long: -123.1162738,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Club16 Trevor Linden Fitness",
        rating: 3.8,
        cityId: 1,
    },
    {
        gymId: 200,
        cityName: "Vancouver",
        address: "1185 W Georgia St #200, Vancouver, BC V6E 4E6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2872573,
        long: -123.1247192,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fitness World",
        rating: 4.3,
        cityId: 1,
    },
    {
        gymId: 201,
        cityName: "Vancouver",
        address: "3055 W Broadway, Vancouver, BC V6K 2G9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2643261,
        long: -123.1730123,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.5,
        cityId: 1,
    },
    {
        gymId: 202,
        cityName: "Vancouver",
        address: "278 E 1st Ave, Vancouver, BC V5T 1A6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.268603,
        long: -123.098128,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "CrossFit BC",
        rating: 4.7,
        cityId: 1,
    },
    {
        gymId: 203,
        cityName: "Vancouver",
        address: "865 Hornby St Unit 202, Vancouver, BC V6Z 2G3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2822014,
        long: -123.1227668,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Studeo",
        rating: 4.4,
        cityId: 1,
    },
    {
        gymId: 204,
        cityName: "Vancouver",
        address: "610 Granville St, Vancouver, BC V6C 3T3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2832382,
        long: -123.1164635,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fitness World",
        rating: 3.8,
        cityId: 1,
    },
    {
        gymId: 205,
        cityName: "Vancouver",
        address: "560 Beatty St L300, Vancouver, BC V6B 2L3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2801579,
        long: -123.1095691,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "West Coast Strength & Movement",
        rating: 5,
        cityId: 1,
    },
    {
        gymId: 206,
        cityName: "Vancouver",
        address: "B102&202, 325 Howe St, Vancouver, BC V6C 3N2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.28653490000001,
        long: -123.1143705,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Elite Performance Fitness",
        rating: 5,
        cityId: 1,
    },
    {
        gymId: 207,
        cityName: "Vancouver",
        address: "124 E Cordova St, Vancouver, BC V6A 1K9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2822127,
        long: -123.1015658,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "CrossFit 604",
        rating: 4.8,
        cityId: 1,
    },
    {
        gymId: 208,
        cityName: "Vancouver",
        address: "555 W 12th Ave, Vancouver, BC V5Z 4B4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2607234,
        long: -123.117342,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fitness World",
        rating: 3.9,
        cityId: 1,
    },
    {
        gymId: 209,
        cityName: "Vancouver",
        address: "2520 Columbia St, Vancouver, BC V5Y 3E9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2626964,
        long: -123.1093696,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Westside Training: Vancouver Gym",
        rating: 4.8,
        cityId: 1,
    },
    {
        gymId: 210,
        cityName: "Vancouver",
        address: "3313 W Broadway, Vancouver, BC V6R 2B1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2644349,
        long: -123.1784407,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Rep1 Fitness | Kitsilano & Vancouver Personal Trainer",
        rating: 4.9,
        cityId: 1,
    },
    {
        gymId: 211,
        cityName: "Vancouver",
        address: "1370 W 4th Ave, Vancouver, BC V6H 4A3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2665753,
        long: -123.1355738,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Collective Fitness Kitsilano",
        rating: 4.9,
        cityId: 1,
    },
    {
        gymId: 212,
        cityName: "Vancouver",
        address: "955 Burrard St, Vancouver, BC V6Z 1Y2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2819066,
        long: -123.1254422,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Robert Lee YMCA",
        rating: 4.3,
        cityId: 1,
    },
    {
        gymId: 213,
        cityName: "Vancouver",
        address: "3479 W Sawmill Cres, Vancouver, BC V5S 0H2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2061084,
        long: -123.0315975,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.6,
        cityId: 1,
    },
    {
        gymId: 214,
        cityName: "Vancouver",
        address: "1055 Dunsmuir St Unit 409, Vancouver, BC V7X 1L3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2864943,
        long: -123.1214363,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Bentall Centre Athletic Club",
        rating: 4.5,
        cityId: 1,
    },
    {
        gymId: 215,
        cityName: "Vancouver",
        address: "856 Homer St #110, Vancouver, BC V6B 2W2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2789333,
        long: -123.1174333,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit Integrated",
        rating: 4.6,
        cityId: 1,
    },
    {
        gymId: 216,
        cityName: "Vancouver",
        address: "428 Pacific St, Vancouver, BC V6Z 3A9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2728522,
        long: -123.1264522,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Club VIVA",
        rating: 4.6,
        cityId: 1,
    },
    {
        gymId: 217,
        cityName: "Vancouver",
        address: "747 Gore Ave, Vancouver, BC V6A 2Z9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2778912,
        long: -123.0971855,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "The Program Fitness (Gym)",
        rating: 5,
        cityId: 1,
    },
    {
        gymId: 218,
        cityName: "Vancouver",
        address: "307 W Pender St, Vancouver, BC V6B 1T3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2823789,
        long: -123.1110496,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Yard Athletics",
        rating: 5,
        cityId: 1,
    },
    {
        gymId: 219,
        cityName: "Vancouver",
        address: "1081 Marinaside Crescent, Vancouver, BC V6Z 2Z4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2736429,
        long: -123.1181171,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Sweat22 Fitness Studio-Yaletown",
        rating: 4.9,
        cityId: 1,
    },
    {
        gymId: 220,
        cityName: "Vancouver",
        address: "2970 W Broadway, Vancouver, BC V6K 2G8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2639807,
        long: -123.1715676,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Citizen",
        rating: 4.7,
        cityId: 1,
    },
    {
        gymId: 221,
        cityName: "Vancouver",
        address: "1348 Granville St, Vancouver, BC V6Z 1M7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2756143,
        long: -123.1281954,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "F45 Training Beach District Vancouver",
        rating: 4.9,
        cityId: 1,
    },
    {
        gymId: 222,
        cityName: "Vancouver",
        address: "211 E Georgia St Unit 10, Vancouver, BC V6A 1Z6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.27868429999999,
        long: -123.0991917,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "F45 Training Vancouver Chinatown",
        rating: 4.6,
        cityId: 1,
    },
    {
        gymId: 223,
        cityName: "Vancouver",
        address: "736 Granville St #10, Vancouver, BC V6Z 1G3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.28188129999999,
        long: -123.1185832,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Groundwork Athletics Inc",
        rating: 4.8,
        cityId: 1,
    },
    {
        gymId: 224,
        cityName: "Vancouver",
        address: "1431 Continental St #701, Vancouver, BC V6Z 1R6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2749501,
        long: -123.1310962,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "House Concepts",
        rating: 4.5,
        cityId: 1,
    },
    {
        gymId: 225,
        cityName: "Vancouver",
        address: "1401 W 8th Ave, Vancouver, BC V6H 1C9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.26477999999999,
        long: -123.136546,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Vancouver Hemlock and 8th For Women",
        rating: 3.6,
        cityId: 1,
    },
    {
        gymId: 226,
        cityName: "Vancouver",
        address: "437 W Hastings St, Vancouver, BC V6B 1L4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2838871,
        long: -123.1114296,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Lagree West- Gastown",
        rating: 4.9,
        cityId: 1,
    },
    {
        gymId: 227,
        cityName: "Vancouver",
        address: "1462 W 8th Ave, Vancouver, BC V6H 1E1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2643751,
        long: -123.1375267,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Kondi Studio",
        rating: 4.4,
        cityId: 1,
    },
    {
        gymId: 228,
        cityName: "Vancouver",
        address: "50, 1055 Canada Pl #50, Vancouver, BC V6C 0C3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2897609,
        long: -123.116804,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "She's Fit",
        rating: 4.6,
        cityId: 1,
    },
    {
        gymId: 229,
        cityName: "Vancouver",
        address: "333 Terminal Ave #102, Vancouver, BC V6A 4C1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2723884,
        long: -123.0960845,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Raincity Athletics - Strength & Conditioning",
        rating: 4.8,
        cityId: 1,
    },
    {
        gymId: 230,
        cityName: "Vancouver",
        address: "2155 Allison Rd, Vancouver, BC V6T 1T5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2661725,
        long: -123.2423678,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Gold\u2019s Gym University Market Place",
        rating: 4.2,
        cityId: 1,
    },
    {
        gymId: 231,
        cityName: "Vancouver",
        address: "950 W 41st Ave, Vancouver, BC V5Z 2N7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2334464,
        long: -123.1267216,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "JCCGV Fitness",
        rating: 4.9,
        cityId: 1,
    },
    {
        gymId: 232,
        cityName: "Vancouver",
        address: "2655 Main St 3rd floor, Vancouver, BC V5T 3E5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2615434,
        long: -123.1012546,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Origins Parkour",
        rating: 4.7,
        cityId: 1,
    },
    {
        gymId: 233,
        cityName: "Vancouver",
        address: "1807 W 1st Ave, Vancouver, BC V6J 5B8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.270777,
        long: -123.146544,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Ron Zalko Fitness and Yoga",
        rating: 3.9,
        cityId: 1,
    },
    {
        gymId: 234,
        cityName: "Vancouver",
        address: "406 Willingdon Ave, Burnaby, BC V5C 5G4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2808442,
        long: -123.0028602,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Dynasty Gym Burnaby",
        rating: 4.8,
        cityId: 1,
    },
    {
        gymId: 235,
        cityName: "Vancouver",
        address: "1020 Mainland St Unit 24 (ground floor, Vancouver, BC V6B 2T5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2764606,
        long: -123.1189558,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit To Be Healthy Fitness & Wellness",
        rating: 5,
        cityId: 1,
    },
    {
        gymId: 236,
        cityName: "Vancouver",
        address: "121 W 2nd Ave, Vancouver, BC V5Y 1A4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2694607,
        long: -123.1073197,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "CMMN GRND Fitness and Social Wellness Collective",
        rating: 4.6,
        cityId: 1,
    },
    {
        gymId: 237,
        cityName: "Vancouver",
        address: "54 W Pender St, Vancouver, BC V6B 6N9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2806682,
        long: -123.1064388,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Iron Lab : Personal Trainer Vancouver",
        rating: 5,
        cityId: 1,
    },
    {
        gymId: 238,
        cityName: "Vancouver",
        address: "4747 Dunbar St, Vancouver, BC V6S 2H2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2436736,
        long: -123.1859593,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Dunbar Fitness Centre",
        rating: 4.2,
        cityId: 1,
    },
    {
        gymId: 239,
        cityName: "Vancouver",
        address: "180 W Georgia St, Vancouver, BC V6B 4P4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.27889039999999,
        long: -123.1130896,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "T Squared Personal Training Vancouver BC",
        rating: 5,
        cityId: 1,
    },
    {
        gymId: 240,
        cityName: "Vancouver",
        address: "54 W Pender St, Vancouver, BC V6B 6N9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.2806699,
        long: -123.1063741,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Powerbox Fitness",
        rating: 4.3,
        cityId: 1,
    },
];
