import { GymCreationAttributes } from "../../database/models/Gym";

export const Winnipeg = [
    {
        gymId: 296,
        cityName: "Winnipeg",
        address: "418 Gertrude Ave, Winnipeg, MB R3L 0M6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8764626,
        long: -97.1420983,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Brickhouse Gym 24/7",
        rating: 4.3,
        cityId: 4,
    },
    {
        gymId: 297,
        cityName: "Winnipeg",
        address: "180 St Anne's Rd, Winnipeg, MB R2M 2Z8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.85739969999999,
        long: -97.1061861,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Full Scene Athletic Centre",
        rating: 4.5,
        cityId: 4,
    },
    {
        gymId: 298,
        cityName: "Winnipeg",
        address: "390 Provencher Blvd N, Winnipeg, MB R2H 0H1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.89353999999999,
        long: -97.1114265,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Acceleration Fitness Center",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 299,
        cityName: "Winnipeg",
        address: "840 Waverley St #4, Winnipeg, MB R3T 5Z7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8490268,
        long: -97.1777379,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "9Round Fitness",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 300,
        cityName: "Winnipeg",
        address: "595 St Anne's Rd, Winnipeg, MB R2M 3G5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8331453,
        long: -97.0891967,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Snap Fitness",
        rating: 3.8,
        cityId: 4,
    },
    {
        gymId: 261,
        cityName: "Winnipeg",
        address: "2 Britannica Rd, Winnipeg, MB R2N 1J4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.814545,
        long: -97.1116141,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "One Family Fitness Centre",
        rating: 4.8,
        cityId: 4,
    },
    {
        gymId: 262,
        cityName: "Winnipeg",
        address: "2361 Ness Ave, Winnipeg, MB R3J 1A5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.88664929999999,
        long: -97.263241,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.3,
        cityId: 4,
    },
    {
        gymId: 263,
        cityName: "Winnipeg",
        address: "686 Springfield Rd, Winnipeg, MB R2G 1N3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.9356438,
        long: -97.0643939,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Snap Fitness",
        rating: 4.6,
        cityId: 4,
    },
    {
        gymId: 264,
        cityName: "Winnipeg",
        address: "1320 Ellice Ave, Winnipeg, MB R3G 0E9, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.893316,
        long: -97.19406300000001,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Planet Fitness",
        rating: 4.5,
        cityId: 4,
    },
    {
        gymId: 265,
        cityName: "Winnipeg",
        address: "1120 Grant Ave, Winnipeg, MB R3M 2A6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8584095,
        long: -97.1627755,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Winnipeg Grant Park Shopping Centre",
        rating: 4.3,
        cityId: 4,
    },
    {
        gymId: 266,
        cityName: "Winnipeg",
        address: "83 Garry St #401, Winnipeg, MB R3C 4J5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8874816,
        long: -97.1361694,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Assiniboine Athletic Club",
        rating: 4.5,
        cityId: 4,
    },
    {
        gymId: 267,
        cityName: "Winnipeg",
        address: "980 Lorimer Blvd, Winnipeg, MB R3P 1C8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8448597,
        long: -97.19899919999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.5,
        cityId: 4,
    },
    {
        gymId: 268,
        cityName: "Winnipeg",
        address: "675 Archibald St, Winnipeg, MB R2J 0Y1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.880076,
        long: -97.098158,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Sweat Equity Fitness",
        rating: 5,
        cityId: 4,
    },
    {
        gymId: 269,
        cityName: "Winnipeg",
        address: "2020 Corydon Ave Unit G, Winnipeg, MB R3P 0N2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.865672,
        long: -97.212096,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit Club West Winnipeg",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 270,
        cityName: "Winnipeg",
        address: "468 Main St, Winnipeg, MB R3B 1B7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8976889,
        long: -97.1393049,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "The Community Gym",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 271,
        cityName: "Winnipeg",
        address: "1795 Henderson Hwy, Winnipeg, MB R2G 1P3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.952873,
        long: -97.0757369,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fit Club North Winnipeg",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 272,
        cityName: "Winnipeg",
        address: "1645 St Mary's Rd, Winnipeg, MB R2N 3W1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8183113,
        long: -97.1115023,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Snap Fitness",
        rating: 4.4,
        cityId: 4,
    },
    {
        gymId: 273,
        cityName: "Winnipeg",
        address: "104 King Edward St E, Winnipeg, MB R3H 0N8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.89115839999999,
        long: -97.2061856,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Brickhouse Gym 24/7",
        rating: 4.5,
        cityId: 4,
    },
    {
        gymId: 274,
        cityName: "Winnipeg",
        address: "1170 Taylor Ave #7, Winnipeg, MB R3M 3Z4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8520481,
        long: -97.1664615,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 275,
        cityName: "Winnipeg",
        address: "430 University Crescent, Winnipeg, MB R3T 2N2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8064758,
        long: -97.13841010000002,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Active Living Centre",
        rating: 4.6,
        cityId: 4,
    },
    {
        gymId: 276,
        cityName: "Winnipeg",
        address: "2855 Pembina Hwy, Winnipeg, MB R3T 2H5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.787287,
        long: -97.15852559999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Planet Fitness",
        rating: 4.4,
        cityId: 4,
    },
    {
        gymId: 277,
        cityName: "Winnipeg",
        address: "1390 Taylor Ave, Winnipeg, MB R3M 3V8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8505325,
        long: -97.1831741,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Reh-Fit Centre",
        rating: 4.6,
        cityId: 4,
    },
    {
        gymId: 278,
        cityName: "Winnipeg",
        address: "240 Graham Ave Unit-102, Winnipeg, MB R3C 0J7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8926515,
        long: -97.1392541,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "9Round Fitness",
        rating: 4.8,
        cityId: 4,
    },
    {
        gymId: 279,
        cityName: "Winnipeg",
        address: "1111 Winnipeg Ave #3, Winnipeg, MB R3E 0S2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.9079097,
        long: -97.17610189999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Movement Fitness and Performance",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 280,
        cityName: "Winnipeg",
        address: "300 Newmarket Blvd, Winnipeg, MB R3T 6G7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8198376,
        long: -97.1699223,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Winnipeg Refinery District - 24/7",
        rating: 4.3,
        cityId: 4,
    },
    {
        gymId: 281,
        cityName: "Winnipeg",
        address: "100 S Town Rd, Winnipeg, MB R3Y 0V8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.79043979999999,
        long: -97.19700619999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Altea Active Winnipeg",
        rating: 4.3,
        cityId: 4,
    },
    {
        gymId: 282,
        cityName: "Winnipeg",
        address: "4910 Roblin Blvd, Winnipeg, MB R3R 0G7, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8571564,
        long: -97.2831155,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness",
        rating: 4.4,
        cityId: 4,
    },
    {
        gymId: 283,
        cityName: "Winnipeg",
        address: "50 Sage Creek Blvd #802, Winnipeg, MB R3X 0J6, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8324509,
        long: -97.0458692,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 284,
        cityName: "Winnipeg",
        address: "1560 Regent Ave W, Winnipeg, MB R2C 3B4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8954584,
        long: -97.0612416,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Planet Fitness Regent",
        rating: 4,
        cityId: 4,
    },
    {
        gymId: 285,
        cityName: "Winnipeg",
        address: "1610 Regent Ave W, Winnipeg, MB R2C 3B5, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.897151,
        long: -97.070683,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Winnipeg Regent and Lagimodiere",
        rating: 4.1,
        cityId: 4,
    },
    {
        gymId: 286,
        cityName: "Winnipeg",
        address: "468 St Anne's Rd Unit B, Winnipeg, MB R2N 3E1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8439942,
        long: -97.0964434,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Blue Sky Fitness Studio",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 287,
        cityName: "Winnipeg",
        address: "166 Meadowood Dr #80, Winnipeg, MB R2M 5G8, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.826158,
        long: -97.10931749999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "9Round Winnipeg MB - Meadowood Dr",
        rating: 4.9,
        cityId: 4,
    },
    {
        gymId: 288,
        cityName: "Winnipeg",
        address: "123 Doncaster St, Winnipeg, MB R3N 2B3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.87198979999999,
        long: -97.2086219,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Rady JCC Fitness Centre",
        rating: 4.5,
        cityId: 4,
    },
    {
        gymId: 289,
        cityName: "Winnipeg",
        address: "50 Burnett Ave, Winnipeg, MB R2G 1C1, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.9316772,
        long: -97.06432989999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Fukumoto Fitness",
        rating: 5,
        cityId: 4,
    },
    {
        gymId: 290,
        cityName: "Winnipeg",
        address: "42 Speers Rd, Winnipeg, MB R2J 1M3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8733349,
        long: -97.0728305,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Atalo Gym",
        rating: 5,
        cityId: 4,
    },
    {
        gymId: 291,
        cityName: "Winnipeg",
        address: "3193 Portage Ave, Winnipeg, MB R3K 0W4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.882757,
        long: -97.28834599999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "GoodLife Fitness Winnipeg Portage and Banting",
        rating: 4.2,
        cityId: 4,
    },
    {
        gymId: 292,
        cityName: "Winnipeg",
        address: "350 North Town Road #310, Winnipeg, MB R3Y 0Y4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.7976288,
        long: -97.19629789999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Orangetheory Fitness",
        rating: 4.7,
        cityId: 4,
    },
    {
        gymId: 293,
        cityName: "Winnipeg",
        address: "430 University Crescent, Winnipeg, MB R3T 2N2, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8065162,
        long: -97.13877,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "University of Manitoba Recreation Services",
        rating: 4.6,
        cityId: 4,
    },
    {
        gymId: 294,
        cityName: "Winnipeg",
        address: "1750 Plessis Rd, Winnipeg, MB R3W 0B3, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.9099719,
        long: -97.0271491,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "Anytime Fitness Transcona",
        rating: 4.3,
        cityId: 4,
    },
    {
        gymId: 295,
        cityName: "Winnipeg",
        address: "400 Spence St, Winnipeg, MB R3B 2S4, Canada",
        url: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        lat: 49.8921511,
        long: -97.15404579999999,
        icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
        name: "The Bill Wedlake Fitness Centre",
        rating: 4.4,
        cityId: 4,
    },
];
